### PR TITLE
Fix up badges links generation: remove / before .svg, correct label for Docker

### LINKED ISSUE #5: Fix URLs to PyPI and Docker hub banners for bidsphysio
This will most likely get reversed when this script is rerun: https://github.com/bids-standard/awesome-bids/blob/main/tools/update_converters_listing.py

Will open an issue to fix the script instead.

_Originally posted by @Remi-Gau in https://github.com/bids-standard/awesome-bids/issues/4#issuecomment-1682358188_

### PR DESCRIPTION
**Pull request by yarikoptic**
Fixes #5 

Also progressed forward submodule (unrelated)

### CODE REVIEW

**Review by Remi-Gau — APPROVED** [review]

**Comment by Remi-Gau** [comment]
thanks @yarikoptic 
FYI just enabled pre-commit ci on this repo so I won't have to push on your branch. (#MarieKondo)

**Comment by effigies** [comment]
@Remi-Gau I think the trailing space that needs cleaning up is generated here:

https://github.com/bids-standard/awesome-bids/blob/d2e9e131383c4e38cd19326a3e9d07b53ea7dcd2/tools/update_converters_listing.py#L26

Is that space necessary in any cases, or should it just be removed and save a bunch of guaranteed pre-commit runs?

**Comment by Remi-Gau** [comment]
yup though I added this also to remove new lines added in the middle of the comments in the original yml comment

will clean this up

**Comment by effigies** [comment]
Ah, got it.

**Comment by Remi-Gau** [comment]
fixed in https://github.com/bids-standard/awesome-bids/commit/8fce2e61d3d56aee4c6ba0b2d477bc554fbdbbda

**Pull request merged**
